#!/usr/bin/env bash
# Open a draft PR using ONLY the dedicated audit PAT.
# Refuses to fall back to ambient gh / SSH / git credentials.
#
# Usage:
#   open-pr.sh <worktree_path> <branch_name> <pr_title> <pr_body_file>

set -euo pipefail

WORKTREE="$1"
BRANCH="$2"
TITLE="$3"
BODY_FILE="$4"

TOKEN_FILE="${KN_AUDIT_TOKEN_FILE:-$HOME/.config/kn-audit/token}"
REPO_SLUG="kwilson21/kaillera-next"

if [[ ! -f "$TOKEN_FILE" ]]; then
  echo "FATAL: $TOKEN_FILE not found. Run scripts/audit-loop/setup.sh first." >&2
  exit 2
fi

# Refuse if the file isn't 0600 — defensive against accidental chmod.
PERMS=$(stat -f '%A' "$TOKEN_FILE" 2>/dev/null || stat -c '%a' "$TOKEN_FILE")
if [[ "$PERMS" != "600" ]]; then
  echo "FATAL: $TOKEN_FILE perms are $PERMS, must be 600." >&2
  exit 2
fi

TOKEN=$(cat "$TOKEN_FILE")
if [[ -z "$TOKEN" ]]; then
  echo "FATAL: token file is empty." >&2
  exit 2
fi

cd "$WORKTREE"

# Push via explicit HTTPS URL with token embedded — bypasses any ambient
# remote (SSH, gh-managed credential helper, osxkeychain, etc.).
PUSH_URL="https://x-access-token:${TOKEN}@github.com/${REPO_SLUG}.git"

# Configure a one-shot remote for this push only — never write the URL to
# .git/config (would persist the token on disk).
echo "Pushing $BRANCH via dedicated PAT..."
git push "$PUSH_URL" "HEAD:refs/heads/$BRANCH" 2>&1 | sed "s/${TOKEN}/***REDACTED***/g"

# gh pr create with GH_TOKEN explicit. Unset GITHUB_TOKEN to prevent
# precedence collisions, and clear gh's hosts.yml-derived auth by setting
# GH_CONFIG_DIR to an isolated dir.
ISOLATED_GH_DIR=$(mktemp -d)
trap 'rm -rf "$ISOLATED_GH_DIR"' EXIT

# Ensure the label exists. `gh label create` is non-idempotent (errors if
# already present), so probe first. Idempotency matters: this script runs
# unattended on a 3-day cron, and we cannot rely on prior runs having
# created the label.
LABEL=automated-tech-debt
if ! GH_TOKEN="$TOKEN" GITHUB_TOKEN="" GH_CONFIG_DIR="$ISOLATED_GH_DIR" \
     gh label list --repo "$REPO_SLUG" --search "$LABEL" --json name --jq '.[].name' 2>/dev/null \
     | grep -qx "$LABEL"; then
  echo "Creating label '$LABEL'..."
  GH_TOKEN="$TOKEN" GITHUB_TOKEN="" GH_CONFIG_DIR="$ISOLATED_GH_DIR" \
    gh label create "$LABEL" \
      --repo "$REPO_SLUG" \
      --color 0E8A16 \
      --description "Auto-generated by /audit-loop skill" 2>&1 | sed "s/${TOKEN}/***REDACTED***/g" || true
fi

echo "Opening draft PR..."
GH_TOKEN="$TOKEN" \
GITHUB_TOKEN="" \
GH_CONFIG_DIR="$ISOLATED_GH_DIR" \
  gh pr create \
    --repo "$REPO_SLUG" \
    --base main \
    --head "$BRANCH" \
    --title "$TITLE" \
    --body-file "$BODY_FILE" \
    --draft \
    --label "$LABEL" 2>&1 | sed "s/${TOKEN}/***REDACTED***/g"
